"""empty message

Revision ID: 82b2b78935ca
Revises: eb60422ef605
Create Date: 2024-10-04 11:18:52.145944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b2b78935ca'
down_revision = 'eb60422ef605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['users_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('users_id')

    # ### end Alembic commands ###
